DROP TABLE IF EXISTS financialentries;

CREATE TABLE financialentries(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
	bank VARCHAR,
	transactionlabel VARCHAR,
	transactioncategory VARCHAR,
	balancechange FLOAT,
	date DATE
);

INSERT INTO financialentries (bank, transactionlabel, transactioncategory, balancechange, date)
VALUES
	('Scotiabank', 'rent', 'rent', 2020.20, '2024-01-01'),
	('TD', 'LCBO', 'booze', 120.1, '2024-01-02')
;
