
-- Drop existing tables
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS budgets CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS authorized_users CASCADE;

-- Create Users table
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Accounts table
CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name VARCHAR(50) NOT NULL,
    owner_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Authorized Users table
CREATE TABLE authorized_users (
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    permission VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, account_id)
);

-- Create Budgets table
CREATE TABLE budgets (
    budget_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    category VARCHAR(50) UNIQUE,
    budget_limit NUMERIC(10, 2),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Transactions table
CREATE TABLE transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    category VARCHAR(50) NOT NULL,
    transaction_name VARCHAR(255),
    amount NUMERIC(10,2) NOT NULL,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE
);

-- Insert sample data
-- Users
INSERT INTO users (username, email, password_hash)
VALUES
    ('user1', 'user@email.com', 'password'),
    ('user2', 'user2@email.com', 'password');

 -- Accounts
 INSERT INTO accounts (account_name, owner_id)
 VALUES
     ('chicken savings', '1'),
     ('parmesan fund', '2'),
     ('alt', '1');

-- Authorized Users
INSERT INTO authorized_users (user_id, account_id, permission)
VALUES
    (1, 1, 'write'),
    (2, 1, 'read'),
    (2, 2, 'write'),
    (1, 3, 'write');

-- Transactions
INSERT INTO transactions (account_id, category, transaction_name, amount, transaction_date)
VALUES
    (1, 'fun', 'microwave brownies', 10.20, '2024-02-10'),
    (1, 'fun', 'grey goose', 99.99, '2023-09-09'),
    (2, 'groceries', 'grand union order', 20.20, '2023-12-27'),
    (3, 'subscriptions', 'netflix', 11.99, '2024-10-07'),
    (3, 'restaurants', 'mcdonalds', 12.23, '1999-03-09');

-- Budgets
INSERT INTO budgets (category, budget_limit)
VALUES
    ('groceries', 200),
    ('fun', 300);


