DROP TABLE IF EXISTS transactions;

CREATE TABLE transactions(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
	bank VARCHAR,
	label VARCHAR,
	category VARCHAR,
	amount FLOAT,
	date DATE
);

INSERT INTO transactions (bank, label, category, amount, date)
VALUES
	('Scotiabank', 'rent', 'rent', 2020.20, '2024-01-01'),
	('TD', 'LCBO', 'booze', 120.1, '2024-01-05')
;
